// Generated by scripts/ascii_resources.py from games/bubble-orbit/assets/sprites.pascii.
// Edit the .pascii resource, not this file.
#ifndef GAMES_BUBBLE_ORBIT_SRC_BUBBLE_ORBIT_ASSETS_H_
#define GAMES_BUBBLE_ORBIT_SRC_BUBBLE_ORBIT_ASSETS_H_

#include "engine/src/ascii_sprite.h"

namespace bubble_assets {

static const AsciiSpriteRun kBubbleRuns[] = {
    {3, 0, 1, kAsciiSoftGlow},
    {4, 0, 5, kAsciiOutline},
    {9, 0, 1, kAsciiSoftGlow},
    {2, 1, 2, kAsciiOutline},
    {4, 1, 5, kAsciiLight},
    {9, 1, 2, kAsciiOutline},
    {1, 2, 1, kAsciiOutline},
    {2, 2, 2, kAsciiLight},
    {4, 2, 2, kAsciiSpecular},
    {6, 2, 1, kAsciiHotGlow},
    {7, 2, 2, kAsciiSpecular},
    {9, 2, 2, kAsciiLight},
    {11, 2, 1, kAsciiOutline},
    {0, 3, 1, kAsciiOutline},
    {1, 3, 2, kAsciiLight},
    {3, 3, 7, kAsciiBase},
    {10, 3, 2, kAsciiLight},
    {12, 3, 1, kAsciiOutline},
    {0, 4, 1, kAsciiOutline},
    {1, 4, 1, kAsciiLight},
    {2, 4, 2, kAsciiBase},
    {4, 4, 2, kAsciiAccentLight},
    {6, 4, 4, kAsciiBase},
    {10, 4, 2, kAsciiLight},
    {12, 4, 1, kAsciiOutline},
    {0, 5, 1, kAsciiOutline},
    {1, 5, 1, kAsciiLight},
    {2, 5, 8, kAsciiBase},
    {10, 5, 2, kAsciiLight},
    {12, 5, 1, kAsciiOutline},
    {0, 6, 1, kAsciiOutline},
    {1, 6, 1, kAsciiLight},
    {2, 6, 7, kAsciiBase},
    {9, 6, 3, kAsciiDark},
    {12, 6, 1, kAsciiOutline},
    {1, 7, 1, kAsciiOutline},
    {2, 7, 1, kAsciiLight},
    {3, 7, 4, kAsciiBase},
    {7, 7, 4, kAsciiDeepShadow},
    {11, 7, 1, kAsciiOutline},
    {2, 8, 1, kAsciiOutline},
    {3, 8, 7, kAsciiDeepShadow},
    {10, 8, 1, kAsciiOutline},
    {3, 9, 1, kAsciiSoftGlow},
    {4, 9, 5, kAsciiOutline},
    {9, 9, 1, kAsciiSoftGlow},
};
static const AsciiSprite kBubble = {
    kBubbleRuns,
    static_cast<int>(sizeof(kBubbleRuns) / sizeof(kBubbleRuns[0])),
    10, 13,
    1, 1,
    0.5f, 0.5f,
    kAsciiBlendAlpha,
};

}  // namespace bubble_assets

#endif  // GAMES_BUBBLE_ORBIT_SRC_BUBBLE_ORBIT_ASSETS_H_
