// Generated by scripts/ascii_resources.py from games/stackfall/assets/sprites.pascii.
// Edit the .pascii resource, not this file.
#ifndef GAMES_STACKFALL_SRC_STACKFALL_ASSETS_H_
#define GAMES_STACKFALL_SRC_STACKFALL_ASSETS_H_

#include "engine/src/ascii_sprite.h"

namespace stackfall_assets {

static const AsciiSpriteRun kBlockRuns[] = {
    {4, 0, 4, kAsciiOutline},
    {2, 1, 1, kAsciiOutline},
    {3, 1, 6, kAsciiLight},
    {9, 1, 1, kAsciiOutline},
    {1, 2, 1, kAsciiOutline},
    {2, 2, 2, kAsciiLight},
    {4, 2, 5, kAsciiSpecular},
    {9, 2, 1, kAsciiLight},
    {10, 2, 1, kAsciiOutline},
    {0, 3, 1, kAsciiOutline},
    {1, 3, 1, kAsciiLight},
    {2, 3, 8, kAsciiBase},
    {10, 3, 1, kAsciiLight},
    {11, 3, 1, kAsciiOutline},
    {0, 4, 1, kAsciiOutline},
    {1, 4, 1, kAsciiLight},
    {2, 4, 2, kAsciiBase},
    {4, 4, 2, kAsciiAccentLight},
    {6, 4, 4, kAsciiBase},
    {10, 4, 1, kAsciiLight},
    {11, 4, 1, kAsciiOutline},
    {0, 5, 1, kAsciiOutline},
    {1, 5, 1, kAsciiLight},
    {2, 5, 8, kAsciiBase},
    {10, 5, 1, kAsciiLight},
    {11, 5, 1, kAsciiOutline},
    {0, 6, 1, kAsciiOutline},
    {1, 6, 1, kAsciiLight},
    {2, 6, 8, kAsciiBase},
    {10, 6, 1, kAsciiLight},
    {11, 6, 1, kAsciiOutline},
    {0, 7, 1, kAsciiOutline},
    {1, 7, 1, kAsciiLight},
    {2, 7, 5, kAsciiBase},
    {7, 7, 4, kAsciiDark},
    {11, 7, 1, kAsciiOutline},
    {1, 8, 1, kAsciiOutline},
    {2, 8, 1, kAsciiLight},
    {3, 8, 4, kAsciiBase},
    {7, 8, 3, kAsciiDark},
    {10, 8, 1, kAsciiOutline},
    {2, 9, 1, kAsciiOutline},
    {3, 9, 1, kAsciiLight},
    {4, 9, 5, kAsciiDeepShadow},
    {9, 9, 1, kAsciiOutline},
    {3, 10, 1, kAsciiOutline},
    {4, 10, 4, kAsciiDeepShadow},
    {8, 10, 1, kAsciiOutline},
    {4, 11, 4, kAsciiOutline},
};
static const AsciiSprite kBlock = {
    kBlockRuns,
    static_cast<int>(sizeof(kBlockRuns) / sizeof(kBlockRuns[0])),
    12, 12,
    0, 0,
    0.5f, 0.5f,
    kAsciiBlendOpaque,
};

}  // namespace stackfall_assets

#endif  // GAMES_STACKFALL_SRC_STACKFALL_ASSETS_H_
