#!/usr/bin/env python3
"""Generate Dragoban's runtime table and provenance document from Microban I."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DRAGOBAN = ROOT / "games/dragoban"
SOURCE = DRAGOBAN / "third-party-levels/david-w-skinner/microban.txt"
HEADER = DRAGOBAN / "src/microban_levels.h"
DOCUMENTATION = DRAGOBAN / "LEVELS.md"

EXPECTED_LEVELS = 155
GRID_WIDTH = 30
GRID_HEIGHT = 17
MAX_BOXES = 16
TILES = frozenset("#@$.+* ")


def parse_levels(text: str) -> list[list[str]]:
    levels: list[list[str]] = []
    current: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        is_map_row = (
            bool(line)
            and set(line) <= TILES
            and any(tile in line for tile in "#@$.+*")
        )
        if is_map_row:
            current.append(line)
        elif current:
            levels.append(current)
            current = []
    if current:
        levels.append(current)
    return levels


def validate(levels: list[list[str]]) -> None:
    if len(levels) != EXPECTED_LEVELS:
        raise ValueError(f"expected {EXPECTED_LEVELS} levels, found {len(levels)}")
    for index, level in enumerate(levels, 1):
        width = max(map(len, level))
        height = len(level)
        boxes = sum(row.count("$") + row.count("*") for row in level)
        goals = sum(row.count(".") + row.count("*") + row.count("+") for row in level)
        players = sum(row.count("@") + row.count("+") for row in level)
        if width > GRID_WIDTH or height > GRID_HEIGHT:
            raise ValueError(f"level {index} is {width}x{height}, larger than runtime grid")
        if boxes > MAX_BOXES:
            raise ValueError(f"level {index} has {boxes} boxes, limit is {MAX_BOXES}")
        if boxes <= 0 or boxes != goals or players != 1:
            raise ValueError(
                f"level {index}: boxes={boxes}, goals={goals}, players={players}"
            )


def runtime_rows(level: list[str]) -> list[str]:
    width = max(map(len, level))
    left = (GRID_WIDTH - width) // 2
    top = (GRID_HEIGHT - len(level)) // 2
    rows = [" " * GRID_WIDTH for _ in range(top)]
    for row in level:
        rows.append((" " * left + row.ljust(width)).ljust(GRID_WIDTH))
    rows.extend(" " * GRID_WIDTH for _ in range(GRID_HEIGHT - len(rows)))
    return rows


def write_header(levels: list[list[str]]) -> None:
    output = [
        "// Generated by scripts/generate_microban_levels.py.",
        "// Source: games/dragoban/third-party-levels/david-w-skinner/microban.txt",
        "// Edit the source collection, not this file.",
        "",
        "const char* const kCuratedLevels[][17] = {",
    ]
    for level in levels:
        output.append("    {")
        output.extend(f'        "{row}",' for row in runtime_rows(level))
        output.append("    },")
    output.extend(
        [
            "};",
            "",
            "const int kCuratedLevelCount =",
            "    static_cast<int>(sizeof(kCuratedLevels) / sizeof(kCuratedLevels[0]));",
            "",
        ]
    )
    HEADER.write_text("\n".join(output))


def write_documentation(levels: list[list[str]]) -> None:
    output = [
        "# Dragoban Level Provenance",
        "",
        "Dragoban embeds the complete 155-level **Microban I** collection by",
        "David W. Skinner, in its original order. The source collection is kept",
        "unchanged at `third-party-levels/david-w-skinner/microban.txt`.",
        "",
        "The runtime representation preserves every wall, player, box, and goal.",
        "It adds only empty exterior cells to fit maps into a `30 x 17` storage grid;",
        "rendering uses each level's active bounds, so smaller maps retain large tiles.",
        "",
        "Skinner permitted his sets to be freely distributed when kept unchanged and",
        "credited with his name and email address. See `../../THIRD_PARTY_NOTICES.md`.",
        "",
        "Legend:",
        "",
        "```text",
        "# wall",
        "@ player",
        "$ box",
        ". goal",
        "* box on goal",
        "+ player on goal",
        "space floor",
        "```",
        "",
    ]
    for index, level in enumerate(levels, 1):
        boxes = sum(row.count("$") + row.count("*") for row in level)
        output.extend(
            [
                f"## Level {index}",
                "",
                f"Source: `Microban I #{index}`. Boxes: {boxes}.",
                "",
                "```text",
                *level,
                "```",
                "",
            ]
        )
    DOCUMENTATION.write_text("\n".join(output))


def main() -> None:
    levels = parse_levels(SOURCE.read_text())
    validate(levels)
    write_header(levels)
    write_documentation(levels)
    print(
        f"generated {len(levels)} levels; grid={GRID_WIDTH}x{GRID_HEIGHT}; "
        f"max_boxes={MAX_BOXES}"
    )


if __name__ == "__main__":
    main()
